### ISSUE TITLE
a64_linux: update to orange-pi-6.1-20230214-2103

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#21] opened 2023-06-13 13:52 UTC

**Comment by cnuke** [comment] 2023-06-20 10:59
@nfeske commit [c1f2431](https://github.com/cnuke/genode-allwinner/commit/c1f24310d6f87fe0382480eb027a6133e831b895) address the problem with the camera driver.

**Comment by cnuke** [comment] 2023-06-20 12:42
Commits [4b1c157](https://github.com/cnuke/genode-imx/commit/4b1c157e2ef97a9e5999a1d70bb51d77830e08ee) and [36e02a4](https://github.com/cnuke/genode-zynq/commit/36e02a440ce745369bfd42a3c7e1f39581a95d58) adapt _imx_ and _zynq_ to the `__get_random_u32_below` promotion.

**Comment by nfeske** [comment] 2023-06-20 14:16
Thank you @cnuke for the follow-up patches. I just ran the latest version on my PinePhone and everything - including the camera and glmark2 - worked as intended, which is great! The only driver I haven't tested yet is the USB driver (for mobile data).

I merged the commit to staging now.

**Closed** 2023-07-14 11:08 UTC
Labels: feature
