### ISSUE TITLE
a64_sd_card_drv: sync operation can take a long time

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode-allwinner#16] opened 2023-03-06 15:07 UTC
With the debug commits https://github.com/cproc/genode/commit/d8a85bab32908d439525d0f9636773b079e17178 and https://github.com/cproc/genode-allwinner/commit/6e073688f5c96aee066b2584b83fd47c6c885e34 the `a64_sd_card_drv.run` test uses the `SYNC` operation instead of the `READ` operation with the sequential test and this test took about 88s on an A64+ board. It seems like `genode_block_notify_peers()` is only called when the next timer signal occurs in this scenario.

**Comment by nfeske** [comment] 2023-03-08 09:18
> [...] but I'm not really sure if this is the correct fix.

@cnuke, @skalk, what do you think?

**Comment by skalk** [comment] 2023-03-08 10:52
To me it seems wrong to notify peers dedicated in case of a SYNC operation. When I understood and remember the model correctly the Io_progress_handler mechanism is used to trigger this in the end of each IO signal. When looking at the driver, to me it seems the problem is the usage of Signal_handler instead of Io_signal_handler.
@cproc could you test commit cdee8fa instead?

**Comment by skalk** [comment] 2023-03-08 10:53
BTW: I could identify several other drivers to suffer from the same problem, I'll open an issue for that.

**Comment by cproc** [comment] 2023-03-08 12:20
> @cproc could you test commit [cdee8fa](https://github.com/genodelabs/genode-allwinner/commit/cdee8fa592056974bb8079bb929afddd46fb1bdb) instead?

Yes, that solves the problem too.

**Comment by skalk** [comment] 2023-03-08 14:04
I was wrong and mixed up backend and frontend regarding I/O signals. @cproc your solution is the prefered one.

**Comment by nfeske** [comment] 2023-03-20 12:30
I merged a6edf8e to staging now.

**Closed as completed** 2023-03-23 13:07 UTC
Labels: bug, fixed
