### ISSUE TITLE
a64_linux: use orange-pi-5.14 as base

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-allwinner#11] opened 2022-10-14 12:32 UTC
The vanilla Linux kernel does not contain all features required for proper support of A64 systems, e.g., PinePhone. The defacto *“vendor kernel”* is the managed by [Ondřej Jirman](http://xnux.eu/index.html).
I propose to switch to that kernel to prevent adding patches to our vanilla based `a64_linux` kernel and to use a kernel that is normally by the Linux based OS' for the PinePhone.

**Comment by cnuke** [comment] 2022-10-14 12:33
Commit [906994d](https://github.com/cnuke/genode-allwinner/commit/906994de8887773586b8be66a42dacd752d1d89e) fixes this issue.

**Comment by cnuke** [comment] 2022-10-22 13:12
Commit [ecbc23d](https://github.com/cnuke/genode-allwinner/commit/ecbc23d09087da6e06fe180f882bdd716d404b5c) fixes the issue and contains every adjustments done to make all current drivers work (the `pinephone_camera_drv` will be prepared afterwards).

I had to change the *.dts* file for the PinePhone as the `&usbphy` node led to a broken extracted *.dts* result. That should be fine as we are only interested in modem (connected via USB) and did not entertain using the OTG port/usb-role-switch but should be addressed at a later date.

**Comment by cnuke** [comment] 2022-11-02 07:55
I tested the `emac_nic_drv` and commit [9dff85b](https://github.com/cnuke/genode-allwinner/commit/9dff85bc07771e2c4e19ef411d1b01fb9d9706e4) resolves the building errors. The driver seems to work (*ping*) but I did not perform a stresstest. That being said I noticed some pecularities:

```
[init -> emac_nic_drv] OF: fdt: No chosen node found, continuing without
[init -> emac_nic_drv] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[init -> emac_nic_drv] clocksource: dde_counter: mask: 0xffffffffffffff max_cycles: 0x1d854df40, max_idle_ns: 3526361616960 ns
[init -> emac_nic_drv] sched_clock: 64 bits at 1000kHz, resolution 1000ns, wraps every 2199023255500ns
[init -> emac_nic_drv] get_random_bytes_arch: leaving buffer unmodified
[init -> emac_nic_drv] get_random_bytes: leaving buffer unmodified
[init -> emac_nic_drv] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[init -> emac_nic_drv] clocksource: Switched to clocksource dde_counter
[init -> emac_nic_drv] mdio_bus: Fixed MDIO Bus: probed
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: IRQ eth_wake_irq not found
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: IRQ eth_lpi not found
[init -> emac_nic_drv] Warning: No clock stmmaceth found for device emac
[init -> emac_nic_drv] Warning: No clock stmmaceth found for device emac
[init -> emac_nic_drv] Warning: No clock pclk found for device emac
[init -> emac_nic_drv] Warning: No clock ptp_ref found for device emac
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: Current syscon value is not the default 6 (expect 0)
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: No HW DMA feature register supported
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: RX Checksum Offload Engine supported
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: COE Type 2
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: TX Checksum insertion supported
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: Normal descriptors
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: Chain mode enabled
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet: device MAC address 02:ba:fe:7b:59:38
[init -> emac_nic_drv] netdev_rss_key_fill leaves buffer unmodified
[init -> emac_nic_drv] mdio_bus: stmmac: probed
[init -> emac_nic_drv] free_pages leaks 2^0 pages
[init -> emac_nic_drv] full_name_hash returns 0
[init -> emac_nic_drv] full_name_hash returns 0
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: PHY [stmmac-0:01] driver [Generic PHY] (irq=POLL)
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: No Safety Features support found
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: No MAC Management Counters available
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: PTP not supported by HW
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: configuring for phy/rgmii-txid link mode
[init -> emac_nic_drv] dwmac-sun8i 1c30000.ethernet eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[init -> emac_nic_drv] create uplink for net device eth0
[init -> nic_router] [uplink] NIC sessions: 1
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> emac_nic_drv] NOHZ tick-stop error: Non-RCU local softirq work is pending, handler #08!!!
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> emac_nic_drv] Warning: attempt to handle the same signal context twice (nested)
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[init -> nic_router] [uplink] dynamic IP config: interface 10.0.0.131/24, gateway 10.0.0.1, P2P 0, DNS server 10.0.0.2
[…]
```

**Comment by nfeske** [comment] 2022-11-02 11:19
Thank you for the build fix, which I promptly merged to staging.

> The driver seems to work (ping) but I did not perform a stresstest. That being said I noticed some pecularities:

This looks like a regression that calls for investigation. I have never seen the `error: Non-RCU local softirq work is pending` messages before.

**Comment by nfeske** [comment] 2022-11-02 11:24
First it would be good to know whether the regression stems from switching the kernel or from 55cc79c765b094987d3036ca3bf683a0a5900c35.

**Comment by cnuke** [comment] 2022-11-04 12:38
@nfeske please merge commit [70d105e](https://github.com/cnuke/genode-allwinner/commit/70d105eb714163c3d61cb02901a9e09399aafbc7) that address the `a64_linux` build problem.

**Comment by nfeske** [comment] 2022-11-04 13:20
Thanks. I merged the fixup.

**Closed** 2022-11-17 14:04 UTC
